trigger: none

parameters:
- name: Branch_tag
  displayName: 'Branch/tag'
  type: string
  default: 'main'

- name: year
  displayName: 'Year'
  type: number
  default: 2024

- name: month
  displayName: 'Month'
  type: number
  default: 6

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'ChangeAutoPython/main.py'
    pythonInterpreter: 'python3'
    arguments: '-y ${{ parameters.year }} -m ${{ parameters.month }}'
    workingDirectory: '$(System.DefaultWorkingDirectory)/ChangeAutoPython'
